// A sanitize schema that knows what mdy emits.
//
// Sanitizing mdy is not the same problem as sanitizing plain markdown. Raw
// HTML is a first-class mdy feature, not an edge case: HTML containers (a
// `<div` line with an indented body) are *source syntax* that expands to raw
// tags, and GitHub alert boxes compile to a `<div class="markdown-alert…">`
// wrapper containing an inline `<svg>` icon. hast-util-sanitize's stock schema
// allows none of that — turn it on unmodified and containers collapse, alert
// icons vanish, and `$.toc()` anchors stop resolving.
//
// So this schema is the default one, widened exactly as far as mdy's own
// output requires, and no further. It is a starting point, not a security
// guarantee for every deployment: if you accept documents from strangers,
// read it and decide for yourself.

import { defaultSchema } from 'rehype-sanitize';

const tagNames = [
  ...defaultSchema.tagNames,
  // The alert icon.
  'svg',
  'path',
  // Structural tags an HTML container is likely to open. Containers are a
  // headline feature; a schema that only permits `div` makes them useless for
  // the semantic markup they exist to produce.
  'article',
  'aside',
  'figure',
  'figcaption',
  'footer',
  'header',
  'hgroup',
  'main',
  'nav',
  'time',
];

// The stock schema does not merely omit `className` — on a dozen tags it pins
// it to one literal value (`section` may only be "footnotes", `li` only
// "task-list-item", `ul`, `a`, `code`, `h2` likewise), and a pin on the tag
// beats the open form on `*`. Those pins exist to protect GitHub's own
// footnote markup and they are precisely wrong here: putting your class on
// your `<section` is the entire point of an HTML container. Left in place they
// do not error, they silently emit `class=""` — the worst kind of bug, since
// the element is still there and only the styling is gone.
const unpinClassName = ([tag, definitions]) => [
  tag,
  definitions.filter((d) => !(Array.isArray(d) && d[0] === 'className')),
];

export const mdySanitizeSchema = {
  ...defaultSchema,
  tagNames,
  attributes: {
    ...Object.fromEntries(Object.entries(defaultSchema.attributes).map(unpinClassName)),
    // Alert boxes, container-authored markup and highlighted code all express
    // themselves through class names, and a class name cannot execute
    // anything — the one caveat being that it can borrow your stylesheet's
    // appearance, so do not treat a CSS class as a trust signal.
    '*': [...defaultSchema.attributes['*'], 'className'],
    svg: ['className', 'viewBox', 'width', 'height', 'ariaHidden', 'fill', 'xmlns', 'role'],
    path: ['d', 'fill', 'fillRule', 'clipRule'],
  },
  // The stock schema rewrites every `id` to `user-content-<id>` to prevent DOM
  // clobbering. That defence costs mdy a feature: heading ids are generated by
  // the same slugger `$.toc()` uses, so prefixing one side and not the other
  // breaks every in-page anchor a document generates. Anchors win here because
  // a table of contents that silently stops working is a bug users will ship
  // without noticing, while clobbering needs an attacker-authored document.
  // If yours are attacker-authored, set `clobberPrefix` back to
  // 'user-content-' and accept the broken anchors, or drop `id` from the
  // allowed attributes entirely.
  clobberPrefix: '',
};
