/*
 * Generate src/parse/alert_table.h from remark-github-blockquote-alert.
 *
 * A GitHub alert — `> [!NOTE]` and its four siblings — renders as a <div> with
 * a title paragraph carrying an octicon, and the icon is an SVG path of some
 * three hundred characters per type. That is data, and copying data by hand is
 * how it drifts: an upgrade to the plugin that redraws an icon would leave
 * this engine writing last year's and nothing would say so.
 *
 * So this reads the plugin mdy-docs actually imports and asks it for each
 * icon, rather than transcribing what the icons are today.
 *
 *   node scripts/generate-alerts.mjs ../.. > src/parse/alert_table.h
 *
 * The path is required for the reason scripts/generate-emoji.mjs gives: the
 * package is in mdy-docs' node_modules and this repo has no package.json.
 */
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';

const mdyDocs = process.argv[2];
if (!mdyDocs) {
  console.error('usage: scripts/generate-alerts.mjs <path to mdy-docs>');
  process.exit(2);
}
const require = createRequire(pathToFileURL(join(mdyDocs, 'package.json')));
const { getAlertIcon } = await import(
  pathToFileURL(require.resolve('remark-github-blockquote-alert')));

/* The five md4c reports through MD_BLOCK_ADMONITION_DETAIL.type, in the order
 * the plugin's own regex lists them. */
const TYPES = ['note', 'tip', 'important', 'warning', 'caution'];

const cString = (s) =>
  '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

const rows = TYPES.map((type) => {
  const icon = getAlertIcon(type);
  const path = icon.children[0].data.hProperties.d;
  if (typeof path !== 'string' || path.length === 0) {
    console.error(`scripts/generate-alerts.mjs: no icon path for ${type}`);
    process.exit(1);
  }
  return { type, path };
});

/* The <svg>'s own attributes, taken from the same place rather than assumed.
 * They are the same for every type; that they are is asserted here so a
 * plugin that starts varying them does not go unnoticed. */
const svg = getAlertIcon('note').data.hProperties;
for (const { type } of rows) {
  const other = getAlertIcon(type).data.hProperties;
  for (const key of Object.keys(svg)) {
    if (JSON.stringify(other[key]) !== JSON.stringify(svg[key])) {
      console.error(`scripts/generate-alerts.mjs: ${type}'s svg ${key} differs`);
      process.exit(1);
    }
  }
}

const out = [];
out.push('/* Generated by scripts/generate-alerts.mjs — do not edit.');
out.push(` * ${rows.length} octicons from remark-github-blockquote-alert. */`);
out.push('#ifndef MDY_ALERT_TABLE_H');
out.push('#define MDY_ALERT_TABLE_H');
out.push('');
out.push('/* The <svg> a title paragraph opens with, attribute for attribute and in');
out.push(' * this order — hast keeps properties in insertion order and the writer');
out.push(' * writes them in it. */');
out.push(`#define MDY_ALERT_VIEWBOX ${cString(svg.viewBox)}`);
out.push(`#define MDY_ALERT_WIDTH   ${cString(svg.width)}`);
out.push(`#define MDY_ALERT_HEIGHT  ${cString(svg.height)}`);
out.push(`#define MDY_ALERT_HIDDEN  ${cString(svg.ariaHidden)}`);
out.push(`#define MDY_ALERT_OCTICON ${cString(svg.className[0])}`);
out.push('');
out.push('static const struct { const char *type; const char *path; } MDY_ALERTS[] = {');
for (const { type, path } of rows) out.push(`    { ${cString(type)}, ${cString(path)} },`);
out.push('};');
out.push('');
out.push('#define MDY_ALERT_COUNT (sizeof MDY_ALERTS / sizeof MDY_ALERTS[0])');
out.push('');
out.push('#endif');
console.log(out.join('\n'));
